// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMotos_API.Datos;

#nullable disable

namespace WebMotos_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230926221716_AlimentarTabla")]
    partial class AlimentarTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMotos_API.Modelos.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Bateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frenos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<double>("Rodado")
                        .HasColumnType("float");

                    b.Property<string>("Suspension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Año = 2018,
                            Bateria = "YTX7L-BS 12V 6Ah",
                            Cilindrada = "124 cc",
                            Color = "Rojo",
                            FechaActualizacion = new DateTime(2023, 9, 26, 19, 17, 16, 595, DateTimeKind.Local).AddTicks(9256),
                            FechaCreacion = new DateTime(2023, 9, 26, 19, 17, 16, 595, DateTimeKind.Local).AddTicks(9241),
                            Frenos = "Disco / Tambor",
                            ImagenUrl = "",
                            Marca = "Yamaha",
                            Modelo = "YBR 125 ED",
                            Motor = "Monocilíndrico, 4 tiempos",
                            Peso = 123,
                            Precio = 1367750.0,
                            Rodado = 18.0,
                            Suspension = "Doble amortiguador"
                        },
                        new
                        {
                            Id = 2,
                            Año = 2017,
                            Bateria = "BB5LB 12V 5Ah",
                            Cilindrada = "107 cc",
                            Color = "Negro",
                            FechaActualizacion = new DateTime(2023, 9, 26, 19, 17, 16, 595, DateTimeKind.Local).AddTicks(9260),
                            FechaCreacion = new DateTime(2023, 9, 26, 19, 17, 16, 595, DateTimeKind.Local).AddTicks(9259),
                            Frenos = "Disco / Tambor",
                            ImagenUrl = "",
                            Marca = "Gilera",
                            Modelo = "Smash 110 Tunning",
                            Motor = "Monocilíndrico, 4 tiempos",
                            Peso = 100,
                            Precio = 623700.0,
                            Rodado = 13.0,
                            Suspension = "Doble amortiguador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
